### PR TITLE
Abiltity to TryParse a System.Guid from string

### PR DESCRIPTION
**Pull request by lgoudriaan**
Thanks for the great library!

The only thing I missed was the option to directly parse a System.Guid, so here it is ;)

The formats in the tests are from here: https://msdn.microsoft.com/en-us/library/system.guid.parse(v=vs.110).aspx#Anchor_2

### CODE REVIEW

**Comment by jasonholloway** [comment]
Hello! The new functionality is great and makes loads of sense - but can you add a round-trip test to make sure the value of the GUID is preserved by going through the parsing? 

Something along the lines of `JsonSerializationTests.DeserializesFromString` - kind of like a sanity check to prove the overall thing works in this scenario

If you do that, I'll happily merge

And - thanks!

**Comment by lgoudriaan** [comment]
No problem. I have changed the unit-test to validate the parsed value.

**Comment by jasonholloway** [comment]
Excellent stuff - thanks for the contribution

**Comment by jasonholloway** [comment]
I'll get a nuget release done shortly

**Pull request merged**
