### PR TITLE
Upgraded to netstandard2.1

### PR DESCRIPTION
**Pull request by HenrikHoyer**
Upgraded library to netstandard2.1
- Removed unneeded package references
- Fixed the "CS0177 The out parameter 'guid' must be assigned to before control leaves the current method" error

Upgraded Test to net8
- Upgraded dependencies to current versions

### CODE REVIEW

**Comment by jasonholloway** [comment]
Hi Henrik, thanks for raising the PR!

I'm largely happy with the idea of updating things, and am frankly puzzled that the non-assignment of the out parameter ever worked (surely this isn't a new thing?)

However, would it be possible to use `TargetFrameworks` to make multiple frameworks available from the same package? I quite like keeping expectations as low as possible in terms of framework version. Conversely, this would also enable us to target `net8` directly as a nice modern option of consumption.

As well as listing the frameworks in the above element, I think we'd also need to retain the original ItemGroup of references behind a condition, as per this blog post: https://markheath.net/post/csproj-conditional-references

**Comment by HenrikHoyer** [comment]
My motivation for this PR was to keep using you library without breaking internal policies (Checkmarx pass required). 

image

netstandard1.0 has been EOL for a long time. It (and the dependencies needed includes several known issues). I don't recommend to keep supporting it.

It is imho completely fine to use netstandard2.x dependencies from net8. 

It is indeed possible to make a multi-targetting version of miniguid. Personally I don't see the value. 

My recommendation is to make a 2.x version with minimal changes (netstandard1.0 to netstandard2.1 upgrade). 

If you want to improve the library (using current language and runtime capabilities like nullability span etc.). I recommend doing it in a 3.x version - since it will break the API. 

The test project is not part of the NuGet package, and you are free to use any version you like. 

Let me know if I can be of any assistance

**Comment by jasonholloway** [comment]
I'd expect multi-targeting would solve your problem - Checkmarx should have enough info to only walk the transitive dependencies actually brought in by your consuming projects, which should only be the 2.1 target. The resultant nuget would have separate folders inside with completely different versions alongside each other - netstandard1.0 would be present in the filesystem, but unreferenced.

There are two use cases to support - the security-conscious on code-analysis treadmills (I'm not bitter about my own working life, honestly!) but also those stuck on immovable apps on legacy frameworks. Multi-targeting would nicely support both.

I agree doing a rewrite with spans would be an obvious improvement, and the code itself would have to diverge at that point, instead of just the supporting transitive dependencies.

**Comment by HenrikHoyer** [comment]
Added multitargeting for 1.0 and 2.1

**Comment by jasonholloway** [comment]
Brilliant, thank you - I'll get the new version published over the weekend

**Pull request merged**
